# Auto Update README

name: CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: tree -d
      - name: update README
        run: tree -d > README.md
        shell: bash {0}
