name: AutoUpdate Category

on:
  push:
    branches: [ "master" ]

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: clean README
        run: cat /dev/null > README.md
      - run: echo '```bash' >> README.md
      - name: update README
        run: cd category && (tree -dLJ 2 > ../data.json;tree -dL 2 >> ../README.md)
      - run: echo '```' >> README.md
      - name: Commit and push changes
        run: |
          git config --global user.name "kok-s0s"
          git config --global user.email "2694308562@qq.com"
          git add -A
          git commit -m "update README.md and data.json"
          git push
